#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

BRANCH_NAME=$(git branch --show-current)
JIRA_TICKET=$(echo "$BRANCH_NAME" | grep -o '[A-Z]\+-[0-9]\+' || true)

COMMIT_MSG_FILE=$1

if [ -n "$JIRA_TICKET" ] && ! grep -q "\[$JIRA_TICKET\]" "$COMMIT_MSG_FILE"; then
  sed -i "" "1s/^/\[$JIRA_TICKET\] /" "$COMMIT_MSG_FILE"
fi